# Generated by Django 4.0.4 on 2022-06-14 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTask', models.CharField(max_length=250)),
                ('contentTask', models.TextField()),
                ('publishedTask', models.TimeField(verbose_name=datetime.datetime(2022, 6, 14, 1, 27, 35, 321612))),
            ],
        ),
    ]
