# Generated by Django 4.0.4 on 2022-06-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpost',
            name='publishedTask',
            field=models.TimeField(),
        ),
    ]
