# Generated by Django 4.0.4 on 2022-06-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_taskpost_publishedtask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskPost',
            new_name='Post',
        ),
    ]
