# Generated by Django 4.0.4 on 2022-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_taskpost_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpost',
            name='checkTask',
            field=models.BooleanField(default=False),
        ),
    ]
