# Generated by Django 4.0.4 on 2022-06-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_taskpost_checktask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpost',
            name='checkTask',
        ),
    ]
