# Generated by Django 4.0.4 on 2022-06-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_taskpost_checktask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpost',
            name='publishedTask',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
